### ISSUE TITLE
No module named 'dotenv'

### ISSUE THREAD

**Issue by hasii2011** [B0G0311/umbrel-cli#1]
Taking our advice from:

https://community.umbrel.com/t/external-storage-mounting-and-usage-for-docker-volumes/15303

I am on an Umbrel Home device with the latest Umbrel 1.0

```
umbrel@umbrel:~/umbrel-cli$ uname -a
Linux umbrel 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

```

executing just the cli 'umbrel' gets the above message

**Comment by B0G0311** [comment]
Umbrel-CLI does not work with Umbrel 1.0 and after due to the way the company changed the code to rely less on  scripts and instead they seem to be ran as services. 

I would like to say that I will be updating this app to fit and provide better cli support to Umbrel but unfortunately as a user who runs UmbrelOS on Linux with a legacy boot system, I have been unable to update to the new base.  I will either be finding/ engineering a work around for this and will post it on github/ the community or I will have to resort to trying to make my own OS around the existing Umbrel base that will hopefully be a better solution for the Linux users.
